name: 'Nextcloud app setup'
description: 'Setup a Nextcloud app for testing'
inputs:
  version:
    description: 'The Nextcloud version to set up, git branch or tag'
    required: false
    default: 'stable27'
  cron:
    description: 'Enable cron'
    required: false
    default: 'true'
  admin-user:
    description: 'Admin user'
    required: false
    default: 'admin'
  admin-password:
    description: 'Admin password'
    required: false
    default: 'admin'
  admin-email:
    description: 'Admin email address'
    required: false
    default: 'admin@nextcloud.local'
  database-type:
    description: 'Database type'
    required: false
    default: 'sqlite'
  database-user:
    description: 'Database user'
    required: false
    default: ''
  database-password:
    description: 'Database password'
    required: false
    default: ''
  database-host:
    description: 'Database host'
    required: false
    default: 'localhost'
  database-port:
    description: 'Database port'
    required: false
    default: ''
  database-name:
    description: 'Database name'
    required: false
    default: ''
  database-table-prefix:
    description: 'Database table prefix'
    required: false
    default: ''
  database-table-space:
    description: 'Database table space'
    required: false
    default: ''
  data-dir:
    description: 'Data directory'
    required: false
    default: ''
  server-dir:
    description: 'Data directory'
    required: false
    default: '../server'

runs:
  using: 'node20'
  main: 'main.js'
