name: Nextcloud app setup

on:
  push:
    paths:
      - '**setup-nextcloud-app**'
      - 'package.json'
      - 'package-lock.json'
      - 'node_modules/**'
  pull_request:
      paths:
      - '**setup-nextcloud-app**'
      - 'package.json'
      - 'package-lock.json'
      - 'node_modules/**'

permissions: {}

jobs:
  setup-nextcloud-app:
    runs-on: ubuntu-latest
    env:
      FILENAME: ".revision"
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: '8.4'

      - name: Server setup
        uses: ./setup-nextcloud/
        with:
          version: 'stable31'
          database-type: 'sqlite'

      - name: Test setup
        run: |
          mkdir appinfo && 
          curl https://raw.githubusercontent.com/nextcloud/app-tutorial/HEAD/appinfo/info.xml -o appinfo/info.xml

      - name: Script test
        uses: ./setup-nextcloud-app/
        with:
          app: 'notestutorial'
          check-code: false
          force: true

      - name: Test setup
        run: cd ../server && ./occ app:list | grep notestutorial
